### ISSUE TITLE
KeyError: 'EOS'

### ISSUE THREAD

**Issue by qq547057827** [Coder-nlper/gpt2-chinese-tf2#1]
Traceback (most recent call last):
  File "train.py", line 91, in <module>
    finished_files)
  File "/home/jovyan/work/gpt2-chinese-tf2/model/data_helper.py", line 125, in load_traindata_ids
    m_len,data_ids = preprocess_triandata2ids(current_data,word2id,max_len,current_end)
  File "/home/jovyan/work/gpt2-chinese-tf2/model/data_helper.py", line 94, in preprocess_triandata2ids
    datas_res[-1].append(word2id['EOS'])
KeyError: 'EOS'

**Comment by white-wolf-tech** [comment]
上传的字典是很久之前的，删除掉重新生成下就好了
